### ISSUE TITLE
Error with matplotlib

### ISSUE THREAD

**Issue by visionok** [DruizrGit/Diiscent#1]
I start the program with

`python3 main.py`

and get this error:

> Traceback (most recent call last):
  File "........./Downloads/Diiscent/main.py", line 3, in <module>
    mpl.style.use('ggplot')
  File "/usr/lib/python3/dist-packages/matplotlib/_api/__init__.py", line 222, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'style'. Did you mean: 'scale'?

Running on Linux Mint 21.3 (Virginia)
Python 3.10.12
matplotlib 3.5.1

Thanks

**Comment by HisDaoMaterials** [comment]
Hi visionok, thanks for notifying me about this. I fixed the error and pushed the changes.
